### ISSUE TITLE
integrate interactive documentation 

### ISSUE THREAD

**Issue by gbinal** [usedgov/usedgov.github.io#9]
e.g. how to do this here - https://autoapi-ed.apps.cloud.gov/swagger-ui/#!/teacher-salary-2/get_teacher_salary_2

**Comment by gbinal** [comment]
In more detail, I want to be able to integrate interactive documentation for the APIs we produce with autoapi [here](https://autoapi-ed.apps.cloud.gov/swagger-ui/#!/teacher-salary-2/get_teacher_salary_2) onto [this page](https://pages.18f.gov/ED-Developer-Hub/details/).  

You can see more examples of providing interactive documentation via github pages with: 
*  [the CFPB](http://cfpb.github.io/api/hmda/console/#!/data/getDataset_get_1) - ([source](https://github.com/cfpb/api/tree/gh-pages/hmda))
* [regulations.gov](http://regulationsgov.github.io/developers/console/) -  ([source](https://github.com/regulationsgov/developers/tree/gh-pages/console))
* [SAM.gov](http://gsa.github.io/sam_api/sam/console/) -  ([source](https://github.com/GSA/sam_api/tree/gh-pages/sam/console))

**Comment by toolness** [comment]
Ok, I'm addressing the interactive documentation in https://github.com/toolness/ED-Developer-Hub/pull/1, but I think that addressing the other query fields needs to be done on the autoapi end, because that's what's generating the metadata describing the API. While we *could* fork or "hack" that metadata on the ED Developer Hub side, I don't think it's a very good idea, because it will then be very easy for the two to fall out-of-sync.

**Comment by gbinal** [comment]
@toolness - Hmm.... I'm not seeing it resolve - https://pages.18f.gov/ED-Developer-Hub/details/

Any thoughts on what might be up?

**Comment by toolness** [comment]
Ah shoot, it looks like our configured value of `site.baseurl` is not actually what 18f-pages is setting it to or something--I'll issue a PR soon!

**Comment by toolness** [comment]
#14 should fix it!

**Comment by gbinal** [comment]
Yep!  It lives!  

I'll follow up further on improving the underlying experience, but great job getting this off the ground.

**Comment by gbinal** [comment]
Closing for now.
